{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001A7FB081E80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=63642): Max retries exceeded with url: /session/4e9058a52136f3b9708f1f8c2a549d25/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A7FB081E80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_create_quotation", "rerun": "0"}}, "suite_name": "src/Specs/test_create_quotation.py"}}}, "date": "June 12, 2024", "start_time": 1718179453.009377, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "1"}