{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001C75CDC22A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=63784): Max retries exceeded with url: /session/e3beca183c4b7748a111b40cbb02392e/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C75CDC22A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_create_product_Success", "rerun": "0"}}, "suite_name": "src/Specs/test_create_product.py"}, "1": {"suite_name": "src/Specs/test_create_quotation.py", "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_create_quotation", "rerun": "0"}}, "status": {"total_pass": 1, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 0}}, "2": {"suite_name": "src/Specs/test_create_quotation_xslx.py", "tests": {"0": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001C75D4641A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=63869): Max retries exceeded with url: /session/a318a6ddcc9347c117cabd6fea87c2a3/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C75D4641A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_File_Barcode_Success", "rerun": "0"}, "1": {"status": "FAIL", "message": "   NameError: name 'webdriver' is not defined\n", "test_name": "test_File_Sku_Success", "rerun": "0"}}, "status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 2, "total_error": 0}}, "3": {"suite_name": "src/Specs/test_login.py", "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_sign_in", "rerun": "0"}}, "status": {"total_pass": 1, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 0}}}}, "date": "June 12, 2024", "start_time": 1718179801.1748934, "total_suite": 4, "status": "FAIL", "status_list": {"pass": "2", "fail": "3", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "5"}